server:
  port: 8011

spring:
  application:
    name: service-consumer

ribbon:
  eager-load:
    enabled: true
    # 必须要配置应用名 否则true没有效果
    clients: service-provider
  # 刷新时间
  ServerListRefreshInterval: 5000
  # 连接建立超时时间 默认2000ms
  ConnectTimeout: 3000
  # 读取数据超时时间 默认5000ms
  ReadTimeout: 6000
  # 是否对所有操作在失败时进行重试 默认false(只对get请求重试) 和MaxAutoRetries/MaxAutoRetriesNextServer配合使用
  # 默认情况下 GET方式请求无论是连接异常还是读取异常都会进行重试 非GET方式请求只有连接异常时才会进行重试
  OkToRetryOnAllOperations: false
  # 同一台实例最大重试次数 不包括首次调用 默认0
  MaxAutoRetries: 1
  # 重试负载均衡其他的实例最大重试次数 不包括首次调用 默认1
  MaxAutoRetriesNextServer: 1

feign:
  hystrix:
    # 开启熔断器功能
    enabled: true
  client:
    config:
      default:
        logger-level: full
logging:
  level:
    com.ljt.study.client: DEBUG
# http://localhost:8088/actuator/hystrix.stream
# http://localhost:8088/hystrix
hystrix:
  command:
    # default配置全局HystrixCommand，断路器配置(详见HystrixCommandProperties)
    default:
      # 默认THREAD,断路器隔离策略，有 THREAD(线程) 和 SEMAPHORE(信号量) 两种可选
      execution.isolation:
        strategy: THREAD
        thread.timeoutInMilliseconds: 16100
  threadpool:
    default:
      maxQueueSize: 50
      queueSizeRejectionThreshold: 50

jetcache:
  areaInCacheName: false
  local:
    default:
      type: caffeine
      keyConvertor: fastjson
  remote:
    default:
      type: redis.lettuce
      keyConvertor: fastjson
      uri: redis://127.0.0.1:6379/
      #uri: redis-sentinel://127.0.0.1:26379,127.0.0.1:26380,127.0.0.1:26381/?sentinelMasterId=mymaster
      #readFrom: slavePreferred