server:
  port: 8080

spring:
  application:
    name: service-consumer

ribbon:
  eager-load:
    enabled: true
    clients: service-provider
  # 刷新时间
  ServerListRefreshInterval: 5000
  # 连接建立超时时间 默认2000ms
  ConnectTimeout: 3000
  # 读取数据超时时间 默认5000ms
  ReadTimeout: 10000
  # 是否对所有操作在失败时进行重试 默认false(只对get请求重试) 和MaxAutoRetries/MaxAutoRetriesNextServer配合使用
  OkToRetryOnAllOperations: true
  # 单个实例重试次数(除去第一次） 默认0
  MaxAutoRetries: 1
  # 单个服务(例如：订单服务 一个服务有多个实例)重试次数(除去第一个服务实例) 默认1
  MaxAutoRetriesNextServer: 1

feign:
  hystrix:
    # 开启熔断器功能
    enabled: true

# http://localhost:8088/actuator/hystrix.stream
# http://localhost:8088/hystrix
hystrix:
  command:
    # default配置全局HystrixCommand，断路器配置(详见HystrixCommandProperties)
    default:
      # 默认THREAD,断路器隔离策略，有 THREAD(线程) 和 SEMAPHORE(信号量) 两种可选
      execution.isolation.strategy: THREAD