server:
  port: 8122

spring:
  application:
    name: alibaba-nacos
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        group: study
#      config:
#        file-extension: yaml
#        shared-configs:
#          - da