server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
#        - StripPrefix=2
#      loadbalancer:
#        use404: true
      metrics:
        enabled: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
#          route-id-prefix: discovery-client_
      routes:
        - id: before_route
          uri: https://example.org
          predicates:
            # RoutePredicateFactory
            - Before=2022-04-16T14:18:00.000+08:00[Asia/Shanghai]
        - id: nacos-service
          uri: lb://alibaba-nacos-service
          predicates:
            - Path=/api/nacos-service/**
          filters:
            - StripPrefix=2
            - AddRequestHeader=X-Request-red, blue
            - AddResponseHeader=X-Response-Red, Blue
            - MapRequestHeader=Blue, X-Request-Red
          metadata:
            connect-timeout: 200
            # a negative value will disable the global response-timeout value
            response-timeout: 200
            iAmNumber: 1
        - id: stomp_route
          uri: lb:ws://alibaba-nacos-service
          predicates:
            - Path=/stomp/**
        - id: socket-io_route
          uri: ws://localhost:8133
          predicates:
            - Path=/socket.io/**

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: '*'