server:
  port: 8080

spring:
  application:
    name: gateway
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.cloud.gateway.config.GatewayRedisAutoConfiguration
  cloud:
    gateway:
      metrics:
        enabled: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 12s
#      loadbalancer:
#        use404: true
      default-filters:
        - StripPrefix=1
        - name: CustomCacheRequestBody
          args:
            bodyClass: java.lang.String
#        - name: RequestRateLimiter
#          args:
#            key-resolver: "#{@customKeyResolver}"
#            redis-rate-limiter.replenishRate: 1
#            redis-rate-limiter.burstCapacity: 5
#            redis-rate-limiter.requestedTokens: 1
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          route-id-prefix: discovery-client_
          include-expression: 'serviceId.startsWith("alibaba-nacos-service")'
          filters:
            - name: RequestSize
              args:
                #B为单位 不能配置MB格式
                maxSize: 20971520
      routes:
        - id: before_route
          uri: https://example.org
          predicates:
            - Before=2022-04-16T14:18:00.000+08:00[Asia/Shanghai]
        - id: nacos-service
          uri: lb://alibaba-nacos-service
          predicates:
            - Path=/api/nacos-service/**
          filters:
            - StripPrefix=1
            - name: RequestSize
              args:
                maxSize: 10MB
            - AddRequestHeader=X-Request, test-req
            - AddResponseHeader=X-Response, test-resp
          metadata:
            connect-timeout: 2000
            # a negative value will disable the global response-timeout value
            response-timeout: 5s
            test-key: 自定义值
        - id: nacos-service-upload_route
          order: -1
          uri: lb://alibaba-nacos-service
          predicates:
            - Path=/api/nacos-service/upload
          filters:
            - StripPrefix=1
            - name: RequestSize
              args:
                maxSize: 50MB
        - id: stomp_route
          uri: lb:ws://alibaba-nacos-service
          predicates:
            - Path=/ws/stomp/**
        - id: socket-io_route
#          uri: ws://localhost:8133
          uri: lb:ws://alibaba-nacos-service-socketIo
          predicates:
            - Path=/ws/socket.io/**
management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    org.springframework.cloud.gateway: INFO