server:
  port: 8125

spring:
  application:
    name: alibaba-nacos-consumer
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
#  cloud:
#    nacos:
#      server-addr: localhost:8848
#      discovery:
        # namespace 和 group 都要和服务提供者一致才能调用
#        group: study

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: admin
    hikari:
      # 最小空闲连接数量
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 连接池名称
      pool-name: hikariCP-${spring.application.name}
      # 用于测试连接的SQL语句
      connection-test-query: SELECT 1
  cloud:
    httpclientfactories:
      ok:
        enabled: true
      apache:
        enabled: false
feign:
  okhttp:
    enabled: true