server:
  port: 8125

spring:
  application:
    name: alibaba-nacos-consumer
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
#  cloud:
#    nacos:
#      server-addr: localhost:8848
#      discovery:
        # namespace 和 group 都要和服务提供者一致才能调用
#        group: study

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.100.100:3306/test?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: admin
    hikari:
      # 最小空闲连接数量
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 连接池名称
      pool-name: hikariCP-${spring.application.name}
      # 用于测试连接的SQL语句
      connection-test-query: SELECT 1
  cloud:
    httpclientfactories:
      ok:
        enabled: true
      apache:
        enabled: false
feign:
  okhttp:
    enabled: true
huafa:
  # 集团网关
  gateway:
#    url: https://apitest.huafagroup.com
#    app-id: gfcsk-dev
#    app-secret: '05438756'
    url: https://api.huafagroup.com
    app-id: gfcsk-pro
    app-secret: 'ZfYKOEw6'
  # 数仓系统
  data:
    url: https://apifront.huafagroup.com
    access-token: cb8VEz5aztFp62LvTvYv5yFIMgMoy9Qt93RjBwIuMe8
  # 客户中心
  customer:
    url: ${huafa.gateway.url}/gf-customer-center-service
  # 交互中心
  interaction:
    url: ${huafa.gateway.url}/gf-interaction-service
  # 权限
  permit:
    url: ${huafa.gateway.url}/gf-market-permit-service
  # oa
  oa:
    url: http://172.16.51.15:50000
    username: PIUSER4OA
    password: oa12345678
    #系统标志
    system-name: kfs
  idm:
    url: ldap://172.16.44.73:1389
    username: 'uid=AUTH_CUSTOMSERVICE,ou=Application,ou=People,o=huafa.com,o=isp'
    password: Huafa2021