server:
  port: 8762

eureka:
  instance:
    # 主机名
    hostname: eureka02.com
  client:
    # 是否将自己注册到Eureka Server,默认为true，由于当前就是server，故而设置成false，表明该服务不会向eureka注册自己的信息
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka01.com:8761/eureka/,http://eureka03.com:8763/eureka/