server:
  port: 80

spring:
  application:
    name: zuul

zuul:
  routes:
    api-service:
      path: /provider/**
      serviceId: service-provider
    api-consumer:
      path: /consumer/**
      serviceId: service-consumer
#  ignored-services:
