spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 200MB
#  cloud:
#    nacos:
#      discovery:
#        group: study
#        namespace: ${spring.profiles.active}
---
server:
  port: 8122
spring:
  config:
    activate:
      on-profile: dev
---
server:
  port: 8123
spring:
  config:
    activate:
      on-profile: test