server:
  port: 8761

spring:
  application:
    name: eurka-server

eureka:
  instance:
    hostname: ${HOSTNAME:localhost}
    # 主要用于区分同一服务集群的不同实例
    instance-id: ${eureka.instance.hostname}:${server.port}
    # 元数据
    metadata-map:
      creator: 李敬堂
  client:
    # 是否将自己注册到Eureka Server 默认为true
    register-with-eureka: false
    # 是否从Eureka Server获取注册信息 默认为true
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    # 是否开启自我保护 默认true
    enable-self-preservation: false
    # 自我保护阈值 默认0.85
    renewal-percent-threshold: 0.85
    # 是否开启从readOnly（第三级缓存）读取注册表 默认true
    use-read-only-response-cache: false
    # readWrite和readOnly同步时间间隔 默认30s Client读取的是readCacheMap
    response-cache-update-interval-ms: 30000
    # 主动失效检测 剔除服务定时任务时间间隔 默认 60s
    eviction-interval-timer-in-ms: 60000

    # 集群节点之间读取超时时间 默认20ms
    peer-node-read-timeout-ms: 1000

logging:
  level:
    com.netflix.eureka: debug

# 集群模式
cluster-zone: http://eureka01.com:8761/eureka/,http://eureka02.com:8762/eureka/,http://eureka03.com:8763/eureka/
# com.netflix.eureka.resources.ApplicationResource
# com.netflix.eureka.util.StatusUtil

# 8761
---
spring:
  profiles: 8761
server:
  port: 8761
eureka:
  instance:
    hostname: eureka01.com
  client:
    service-url:
      defaultZone: ${cluster-zone}
# 8762
---
spring:
  profiles: 8762
server:
  port: 8762
eureka:
  instance:
    hostname: eureka02.com
  client:
    service-url:
      defaultZone: ${cluster-zone}
# 8763
---
spring:
  profiles: 8763
server:
  port: 8763
eureka:
  instance:
    hostname: eureka03.com
  client:
    service-url:
      defaultZone: ${cluster-zone}