server:
  port: 8761

spring:
  application:
    name: eurka-server

eureka:
  instance:
    # 主机名
    hostname: ${HOSTNAME:localhost}
    # 服务之间调用时如果为true,则优先使用IP地址进行调用，否则使用主机名eureka.instance.hostname进行调用，默认false
#    prefer-ip-address: true
    metadata-map:
      creator: '李敬堂'
  client:
    # 是否将自己注册到Eureka Server,默认为true，由于当前就是server，故而设置成false，表明该服务不会向eureka注册自己的信息
    register-with-eureka: false
    # 是否从eureka server获取注册信息，由于单节点，不需要同步其他节点数据，用false
    fetch-registry: false
    # 设置服务注册中心的URL，用于client和server端交流
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    # 是否开启自我保护
    enable-self-preservation: false
    # 自我保护阈值
    renewal-percent-threshold: 0.6
    # 剔除服务任务时间间隔
    eviction-interval-timer-in-ms: 5000
    # 关闭从readOnly读注册表
    use-read-only-response-cache: false
    # readWrite 和 readOnly 同步时间间隔
    response-cache-update-interval-ms: 1000