server:
  port: 8001

eureka:
  instance:
    metadata-map:
      grey-version: v1

test:
  sets:
    - set1
  # map 结构 移除key 经测试 不能刷新
  map:
    k1:
      - hello
    k3:
      - hello
  itemMap:
    k2:
      key: hello
      name: world